git config --global user.email 1114891937@qq.com
git config --global user.name WeiXia
git checkout main
git reset --hard origin/main
git pull
conda activate django
python /home/xw/backend/manage.py runserver 0.0.0.0:8000
(base) xw@VM-20-3-ubuntu:~/backend$ git config --global user.email 1114891937@qq
.com
(base) xw@VM-20-3-ubuntu:~/backend$ git config --global user.name WeiXia
(base) xw@VM-20-3-ubuntu:~/backend$ git checkout main
Already on 'main'
Your branch is up to date with 'origin/main'.
(base) xw@VM-20-3-ubuntu:~/backend$ git reset --hard origin/main
HEAD is now at 3239795 utils
(base) xw@VM-20-3-ubuntu:~/backend$ git pull
Already up to date.
(base) xw@VM-20-3-ubuntu:~/backend$ conda activate django
(django) xw@VM-20-3-ubuntu:~/backend$ python /home/xw/backend/manage.py runserve
r 0.0.0.0:8000
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
July 31, 2022 - 15:22:00
Django version 4.0.4, using settings 'backend.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

